# Eigendecomposition

https://github.com/mikexcohen/LinAlg4DataScience/blob/main/LA4DS_ch13.ipynb

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
matrix = np.array([[1,2], [3,4]])

# Finding eigenvectors
evals,evecs = np.linalg.eig(matrix)

print(evals)
print(evecs)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [7]:
D = np.diag(evals)
print(D)

[[-0.37228132  0.        ]
 [ 0.          5.37228132]]


In [ ]:
print(matrix @ evecs)
print(evecs @ D)

[[ 0.30697009 -2.23472698]
 [-0.21062466 -4.88542751]]
[[ 0.30697009 -2.23472698]
 [-0.21062466 -4.88542751]]


In [12]:
evecs@D

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [ ]:
# Special properties 
A = np.random.randint(-3, 4, (3,3))
A = A.T@A

# eigendecomp
L,V = np.linalg.eig(A)

# all pairwise dot products
print(np.dot(V[:,0],V[:,1]))
print(np.dot(V[:,0],V[:,2]))
print(np.dot(V[:,1],V[:,2]))



-3.903127820947816e-16
0.0
-8.326672684688674e-17
