# Row Reduction and LU Decomposition

https://github.com/mikexcohen/LinAlg4DataScience/blob/main/LA4DS_ch10.ipynb

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# sympy library for RREF
import sympy as sym

# scipy for LU
import scipy.linalg


# used to create non-regular subplots
import matplotlib.gridspec as gridspec

In [2]:
# Working with matrix equations
A = np.random.randn(4,4)
B = np.random.randn(4,4)

# Solve for X (AX = B)
A_inv = np.linalg.inv(A)
X1 = A_inv @ B
X2 = B @ A_inv
print(B)
print(A@X1)
print(A@X2)


[[ 0.11352281 -0.3667141   0.85216772 -0.78221107]
 [-0.57732208  0.15290625 -2.14498741  0.08893802]
 [ 0.43600567 -1.90690989  0.77993125 -0.15557051]
 [ 0.01874306 -0.26426096  0.73816239  0.63936982]]
[[ 0.11352281 -0.3667141   0.85216772 -0.78221107]
 [-0.57732208  0.15290625 -2.14498741  0.08893802]
 [ 0.43600567 -1.90690989  0.77993125 -0.15557051]
 [ 0.01874306 -0.26426096  0.73816239  0.63936982]]
[[ 9.10202121e-01  3.35508185e+00 -2.36325619e+00  8.54480211e-03]
 [ 1.46609779e+01  1.41053786e+02 -6.76364185e+01  6.94715477e+01]
 [ 1.41656464e+01  1.36332127e+02 -6.54857548e+01  6.70745465e+01]
 [-1.59644495e+01 -1.52208446e+02  7.29784167e+01 -7.47925030e+01]]
