# Row Reduction and LU Decomposition

https://github.com/mikexcohen/LinAlg4DataScience/blob/main/LA4DS_ch10.ipynb

In [2]:
import numpy as np
import matplotlib.pyplot as plt

# sympy library for RREF
import sympy as sym

# scipy for LU
import scipy.linalg


# used to create non-regular subplots
import matplotlib.gridspec as gridspec

In [2]:
# Working with matrix equations
A = np.random.randn(4,4)
B = np.random.randn(4,4)

# Solve for X (AX = B)
A_inv = np.linalg.inv(A)
X1 = A_inv @ B
X2 = B @ A_inv
print(B)
print(A@X1)
print(A@X2)


[[ 0.11352281 -0.3667141   0.85216772 -0.78221107]
 [-0.57732208  0.15290625 -2.14498741  0.08893802]
 [ 0.43600567 -1.90690989  0.77993125 -0.15557051]
 [ 0.01874306 -0.26426096  0.73816239  0.63936982]]
[[ 0.11352281 -0.3667141   0.85216772 -0.78221107]
 [-0.57732208  0.15290625 -2.14498741  0.08893802]
 [ 0.43600567 -1.90690989  0.77993125 -0.15557051]
 [ 0.01874306 -0.26426096  0.73816239  0.63936982]]
[[ 9.10202121e-01  3.35508185e+00 -2.36325619e+00  8.54480211e-03]
 [ 1.46609779e+01  1.41053786e+02 -6.76364185e+01  6.94715477e+01]
 [ 1.41656464e+01  1.36332127e+02 -6.54857548e+01  6.70745465e+01]
 [-1.59644495e+01 -1.52208446e+02  7.29784167e+01 -7.47925030e+01]]


In [5]:
# the matrix converted to sympy
M = np.array([[1,1,4],[-1/2,1,2]])
symMat = sym.Matrix(M)

# RREF
symMat.rref()[0]

Matrix([
[1, 0, 1.33333333333333],
[0, 1, 2.66666666666667]])

In [ ]:
# LU decomposition
A = np.array([[2,2,4],[1,0,3],[2,1,2]])
_,L,U = scipy.linalg.lu(A)

print("L: "), print(L)
print("U: "), print(U)

print(np.linalg.inv(L))

L: 
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  1.  1. ]]
U: 
[[ 2.  2.  4.]
 [ 0. -1.  1.]
 [ 0.  0. -3.]]
[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [-0.5 -1.   1. ]]
[[ 9  6 15]
 [ 6  5 10]
 [15 10 29]]


In [ ]:
# Exercise 10-2

A1 = np.random.randn(6,3)
A2 = np.random.randn(3,8)
A = A1 @ A2

_,L,U = scipy.linalg.lu(A)

print("L: "), print(L)
print(np.linalg.matrix_rank(L))
print("U: "), print(U)
print(np.linalg.matrix_rank(U))


L: 
[[ 1.          0.          0.          0.          0.          0.        ]
 [-0.79151911  1.          0.          0.          0.          0.        ]
 [ 0.72338764 -0.03228024  1.          0.          0.          0.        ]
 [-0.32008062 -0.36214958 -0.15544233  1.          0.          0.        ]
 [ 0.75437284 -0.35112617  0.65527739 -0.4         1.          0.        ]
 [ 0.17486291  0.13063155 -0.8521345   0.          0.          1.        ]]
6
U: 
[[ 1.96988284e+00 -1.91429277e-01 -1.22310363e+00  1.30995309e+00
  -2.57115506e+00 -6.78099628e-01  1.32668766e+00 -6.08181535e-01]
 [ 0.00000000e+00  8.25602476e-01 -1.73522499e+00 -1.72438884e+00
  -2.84003515e-01 -1.02557373e+00  4.24732002e+00  1.71160230e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.98328587e-01 -2.91143536e+00
   3.81821562e+00 -3.54805481e-02  1.79348116e+00  1.95142001e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  5.55111512e-16
  -7.21644966e-16  1.11022302e-16  0.00000000e+00 -3.33066907e-16]
 [ 0.00

In [18]:
# Exercise 10-4

A = np.random.randn(4,4)

P,L,U = scipy.linalg.lu(A)

A_inv = np.linalg.inv(U) @ np.linalg.inv(L) @ P.T

print(A@A_inv)

[[ 1.00000000e+00  7.96995269e-18 -3.10764903e-17 -1.62990484e-17]
 [-5.45536167e-17  1.00000000e+00  5.68283335e-17  5.85525882e-17]
 [-6.03917925e-19  1.90894172e-17  1.00000000e+00 -7.82271920e-17]
 [ 7.85980137e-17  2.92358180e-17 -6.08258566e-18  1.00000000e+00]]
