# Matrix inverse

https://github.com/mikexcohen/LinAlg4DataScience/blob/main/LA4DS_ch08.ipynb

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Matrix inverse
A = np.array([[1,4],[2,7]])
Ainv = np.linalg.inv(A)
Ainv@A

array([[1., 0.],
       [0., 1.]])

In [16]:
# One-sided inverse
T = np.random.randint(-10,11,size=(20,4))
TtT = T.T@T
print(TtT)
TtT_inv = np.linalg.inv(TtT)
print(TtT_inv)

(TtT_inv@T.T)@T

[[ 596 -103 -185 -146]
 [-103  849 -156  106]
 [-185 -156  765 -170]
 [-146  106 -170 1048]]
[[ 2.01375524e-03  3.16173305e-04  6.29385070e-04  3.50657783e-04]
 [ 3.16173305e-04  1.28093906e-03  3.30585059e-04 -3.18881469e-05]
 [ 6.29385070e-04  3.30585059e-04  1.59640804e-03  3.13203789e-04]
 [ 3.50657783e-04 -3.18881469e-05  3.13203789e-04  1.05708094e-03]]


array([[ 1.00000000e+00,  1.56125113e-17,  4.16333634e-17,
         5.89805982e-17],
       [-8.67361738e-18,  1.00000000e+00, -9.71445147e-17,
         2.77555756e-17],
       [-2.25514052e-17, -4.51028104e-17,  1.00000000e+00,
         6.93889390e-18],
       [-3.12250226e-17,  8.67361738e-18, -2.77555756e-17,
         1.00000000e+00]])

In [25]:
W = np.random.randint(-10,11,size=(4,10))
print(W)
WWt = W@W.T
print(WWt)

WWt_inv = np.linalg.inv(WWt)
print(WWt_inv@WWt)

R = W.T@WWt_inv
print(R)

W@R

[[ 10   5   6   7  -3   6   3  -1   5  -8]
 [ 10  -6  -6   1   8 -10   8  -5   1  -9]
 [ -9  -6  -3   1  -7  -9  10  -9   1   5]
 [ -3   3  -7  -7   8   3  -6   4   1   3]]
[[ 354   63 -160 -153]
 [  63  508   80  -73]
 [-160   80  464 -140]
 [-153  -73 -140  251]]
[[ 1.00000000e+00  5.72458747e-17  2.98372438e-16 -5.20417043e-18]
 [-1.65882932e-17  1.00000000e+00  2.64545330e-17  1.33356867e-17]
 [-2.05564732e-16 -1.91686944e-16  1.00000000e+00  3.80771803e-16]
 [-3.50414142e-16 -7.28583860e-17  1.24900090e-16  1.00000000e+00]]
[[ 0.00462158  0.02074076 -0.02683047 -0.01806808]
 [ 0.0446216  -0.01372706  0.0185533   0.04550794]
 [-0.01979085 -0.01340726 -0.02910808 -0.0600871 ]
 [ 0.00945259 -0.00238451 -0.00127393 -0.02353057]
 [-0.00684313  0.02254185 -0.01322124  0.0268828 ]
 [ 0.03892515 -0.02086703  0.00788487  0.03400851]
 [ 0.03044224  0.00881211  0.03569691  0.01712556]
 [-0.02559763 -0.00421476 -0.03338438 -0.01951365]
 [ 0.06443089 -0.00345693  0.04534956  0.06754785]
 [-0.0

array([[ 1.00000000e+00,  2.77555756e-17,  1.38777878e-16,
        -4.16333634e-17],
       [ 5.37764278e-17,  1.00000000e+00, -1.04083409e-17,
         1.07552856e-16],
       [-3.17454396e-16, -6.93889390e-17,  1.00000000e+00,
         2.39391840e-16],
       [ 4.68375339e-17, -1.38777878e-17,  2.74086309e-16,
         1.00000000e+00]])