# Orthogonal Matrices and QR Decomposition

https://github.com/mikexcohen/LinAlg4DataScience/blob/main/LA4DS_ch09.ipynb

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
Q1 = np.array([ [1,-1], [1,1]] / np.sqrt(2))
print(np.dot(Q1[:,0], Q1[:,1]))
print(np.linalg.norm(Q1[:,0]))
print(Q1.T @ Q1)
print(Q1 @ Q1.T)


0.0
0.9999999999999999
[[1.00000000e+00 2.23711432e-17]
 [2.23711432e-17 1.00000000e+00]]
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]


In [14]:
# Exercise 9-2
# create the matrix 
m = 4
n = 4
A = np.random.randn(m,n)

# initialize
Q = np.zeros((m,n))

# the GS algo
for i in range(n):
    
    # initialize
    Q[:,i] = A[:,i]
    
    # orthogonalize
    a = A[:,i] # convenience
    for j in range(i): # only to earlier cols
        q = Q[:,j] # convenience
        Q[:,i]=Q[:,i]-np.dot(a,q)/np.dot(q,q)*q
    
    # normalize
    Q[:,i] = Q[:,i] / np.linalg.norm(Q[:,i])

    
# "real" QR decomposition for comparison
Q2,R = np.linalg.qr(A)


# note the possible sign differences.
# seemingly non-zero columns will be 0 when adding
print( np.round( Q-Q2 ,10) ), print(' ')
print( np.round( Q+Q2 ,10) )

[[-0.         -0.46548382  0.          0.        ]
 [ 0.          1.4342574  -0.          0.        ]
 [-0.          1.14496801  0.         -0.        ]
 [-0.          0.64442129  0.         -0.        ]]
 
[[-0.03507033  0.          1.93700692 -0.17349081]
 [ 1.28780814  0.          0.39962003  0.35321346]
 [-0.95463863  0.          0.139096   -1.32603381]
 [-1.19540176  0.          0.26260296  1.44456759]]


In [17]:
# QR

A = np.random.randn(3,3)
print(A)
Q,R = np.linalg.qr(A)
print(Q @ R)

[[ 1.28196775 -0.47262482  0.84976956]
 [ 0.07005207  0.57925829 -0.00915306]
 [-0.29722284  1.04224044  1.92344317]]
[[ 1.28196775 -0.47262482  0.84976956]
 [ 0.07005207  0.57925829 -0.00915306]
 [-0.29722284  1.04224044  1.92344317]]


In [21]:
A = np.array([ [1,-1] ]).T
print(A)
Q,R = np.linalg.qr(A, 'complete')
print(Q)
print(R)

[[ 1]
 [-1]]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[[-1.41421356]
 [ 0.        ]]


In [14]:
# Exercie 9-3
A = np.random.randn(6,6)
U,R = np.linalg.qr(A)

Q,R2 = np.linalg.qr(U)

# Modulate the norms
for i in range(U.shape[0]):
  U[:,i] = U[:,i]*(10+i)

Q,R = np.linalg.qr(U)

U[0,3] = 0 # this is q_{1,4}
q,r = np.linalg.qr(U)
print(r)

[[ 1.00000000e+01 -8.88178420e-16  8.88178420e-16 -1.90284474e+00
   2.22044605e-16 -1.77635684e-15]
 [ 0.00000000e+00  1.10000000e+01  3.55271368e-15  4.03158204e-01
  -2.22044605e-16 -3.55271368e-15]
 [ 0.00000000e+00  0.00000000e+00  1.20000000e+01  1.65046194e+00
   8.88178420e-16  1.11022302e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.24054317e+01
   9.63696362e-02  1.55119799e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.39996683e+01 -1.06779948e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.49195734e+01]]


In [15]:
# Exercise 9-7
# the matrix
A = np.random.randn(10,4)

# get R
_,R = np.linalg.qr(A,'complete')

# examine R
np.round(R,3)

array([[-3.582,  0.385, -1.16 ,  0.199],
       [ 0.   , -2.87 ,  0.21 ,  0.584],
       [ 0.   ,  0.   ,  2.816,  0.093],
       [ 0.   ,  0.   ,  0.   ,  1.875],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ]])

In [25]:
R_sq = R[0:4,]
Rsub_inv = np.linalg.inv(R_sq)

Rleftinv = np.linalg.pinv(R)

# print out both
print('Full inverse of R submatrix:')
print(np.round(Rsub_inv,3)), print(f'\n\n')

print('Left inverse of R:')
print(np.round(Rleftinv,3))

Full inverse of R submatrix:
[[-0.279 -0.037 -0.112  0.047]
 [-0.    -0.348  0.026  0.107]
 [ 0.     0.     0.355 -0.018]
 [ 0.     0.     0.     0.533]]



Left inverse of R:
[[-0.279 -0.037 -0.112  0.047  0.     0.     0.     0.     0.     0.   ]
 [ 0.    -0.348  0.026  0.107  0.     0.     0.     0.     0.     0.   ]
 [-0.     0.     0.355 -0.018  0.     0.     0.     0.     0.     0.   ]
 [ 0.    -0.     0.     0.533  0.     0.     0.     0.     0.     0.   ]]
