# Orthogonal Matrices and QR Decomposition

https://github.com/mikexcohen/LinAlg4DataScience/blob/main/LA4DS_ch09.ipynb

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
Q1 = np.array([ [1,-1], [1,1]] / np.sqrt(2))
print(np.dot(Q1[:,0], Q1[:,1]))
print(np.linalg.norm(Q1[:,0]))
print(Q1.T @ Q1)
print(Q1 @ Q1.T)


0.0
0.9999999999999999
[[1.00000000e+00 2.23711432e-17]
 [2.23711432e-17 1.00000000e+00]]
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]


In [14]:
# Exercise 9-2
# create the matrix 
m = 4
n = 4
A = np.random.randn(m,n)

# initialize
Q = np.zeros((m,n))

# the GS algo
for i in range(n):
    
    # initialize
    Q[:,i] = A[:,i]
    
    # orthogonalize
    a = A[:,i] # convenience
    for j in range(i): # only to earlier cols
        q = Q[:,j] # convenience
        Q[:,i]=Q[:,i]-np.dot(a,q)/np.dot(q,q)*q
    
    # normalize
    Q[:,i] = Q[:,i] / np.linalg.norm(Q[:,i])

    
# "real" QR decomposition for comparison
Q2,R = np.linalg.qr(A)


# note the possible sign differences.
# seemingly non-zero columns will be 0 when adding
print( np.round( Q-Q2 ,10) ), print(' ')
print( np.round( Q+Q2 ,10) )

[[-0.         -0.46548382  0.          0.        ]
 [ 0.          1.4342574  -0.          0.        ]
 [-0.          1.14496801  0.         -0.        ]
 [-0.          0.64442129  0.         -0.        ]]
 
[[-0.03507033  0.          1.93700692 -0.17349081]
 [ 1.28780814  0.          0.39962003  0.35321346]
 [-0.95463863  0.          0.139096   -1.32603381]
 [-1.19540176  0.          0.26260296  1.44456759]]


In [17]:
# QR

A = np.random.randn(3,3)
print(A)
Q,R = np.linalg.qr(A)
print(Q @ R)

[[ 1.28196775 -0.47262482  0.84976956]
 [ 0.07005207  0.57925829 -0.00915306]
 [-0.29722284  1.04224044  1.92344317]]
[[ 1.28196775 -0.47262482  0.84976956]
 [ 0.07005207  0.57925829 -0.00915306]
 [-0.29722284  1.04224044  1.92344317]]


In [21]:
A = np.array([ [1,-1] ]).T
print(A)
Q,R = np.linalg.qr(A, 'complete')
print(Q)
print(R)

[[ 1]
 [-1]]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[[-1.41421356]
 [ 0.        ]]
