# Row Reduction and LU Decomposition

https://github.com/mikexcohen/LinAlg4DataScience/blob/main/LA4DS_ch10.ipynb

In [2]:
import numpy as np
import matplotlib.pyplot as plt

# sympy library for RREF
import sympy as sym

# scipy for LU
import scipy.linalg


# used to create non-regular subplots
import matplotlib.gridspec as gridspec

In [5]:
# Working with matrix equations
A = np.random.randn(4,4)
B = np.random.randn(4,4)

# Solve for X (AX = B)
A_inv = np.linalg.inv(A)
X1 = A_inv @ B
X2 = B @ A_inv
print(B)
print(A@X1)
print(A@X2)


[[-0.6155153   0.8505337  -0.12123128 -0.696858  ]
 [-0.24761165  0.37825983 -2.51498157 -1.06538607]
 [ 2.12118469  0.63566275 -0.74433933  1.43811142]
 [ 1.5031443   0.50205928  3.05350629 -0.31153646]]
[[-0.6155153   0.8505337  -0.12123128 -0.696858  ]
 [-0.24761165  0.37825983 -2.51498157 -1.06538607]
 [ 2.12118469  0.63566275 -0.74433933  1.43811142]
 [ 1.5031443   0.50205928  3.05350629 -0.31153646]]
[[-0.28372054  0.538995    2.98292465  1.34709622]
 [-1.20653393 -1.30797414 -2.70534801 -2.78119943]
 [-0.30348121 -1.15294087  0.05003131 -3.61867994]
 [ 1.24833955 -0.45833933  1.13817171  0.2485321 ]]
